"""F9: governance_wrapper_registrations (wrapper coverage registry).

Revision ID: f9a1b2c3d4e5
Revises: a1b2c3d4e5f6
Create Date: 2026-04-15 00:00:00.000000

Adds the F9 wrapper coverage registry table. This table is the Postgres
mirror for the in-process :class:`WrapperRegistry` so compliance reports
generated by peer replicas can quantify coverage across the whole fleet.

CRITICAL DBA NOTICE — MUTABLE STATE TABLE, NOT AN AUDIT LOG
============================================================
This table is EXPLICITLY EXCLUDED from the audit append-only invariant.
The governance SDK enforces append-only semantics on
``governance_audit_events`` via revoked UPDATE/DELETE grants. This
table, by contrast, is operational state:

* ``last_seen_at`` is updated in place on every SDK flush cycle
  (heartbeat).
* Rows are pruned opportunistically on flush — rows older than 30 days
  are DELETEd in batches of 100.

Both UPDATE and DELETE are legitimate and required. Any DBA hardening
pass that revokes UPDATE/DELETE on this table will BREAK the SDK.

See decisions/2026-04-15-f9-wrapper-coverage-design.md section 3 for
the full architectural rationale.

Spoofing prevention: a trigger rejects INSERTs for any ``agent_id`` not
present in ``governance_policies``. Because the policies PK is
composite (``agent_id``, ``policy_type``), a standard foreign key
constraint against ``agent_id`` alone is not supported. The trigger is
the semantic equivalent.

Hostname PII: rows store ``hostname_hash`` (HMAC-SHA256 keyed by a
per-deployment workspace salt), never raw hostnames. GDPR Art. 4(1)
compliant.
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9a1b2c3d4e5"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create governance_wrapper_registrations with spoofing-prevention trigger."""
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS governance_wrapper_registrations (
            id              BIGSERIAL PRIMARY KEY,
            agent_id        TEXT NOT NULL,
            provider        TEXT NOT NULL,
            hostname_hash   TEXT NOT NULL,
            instance_id     UUID NOT NULL,
            sdk_version     TEXT,
            registered_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (agent_id, provider, instance_id)
        );
        """
    )
    # MUTABLE STATE CARVE-OUT — must live in the DDL, not just the PRD.
    op.execute(
        """
        COMMENT ON TABLE governance_wrapper_registrations IS
        'F9 wrapper coverage registry. MUTABLE STATE — NOT an audit log. '
        'Explicitly excluded from the audit append-only invariant: '
        'UPDATEs to last_seen_at (heartbeats) and DELETEs from the '
        '30-day opportunistic prune are legitimate and required. '
        'Do NOT apply revoked UPDATE/DELETE grants to this table. '
        'See decisions/2026-04-15-f9-wrapper-coverage-design.md section 3.';
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_wrapper_reg_last_seen
            ON governance_wrapper_registrations (last_seen_at);
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_wrapper_reg_agent
            ON governance_wrapper_registrations (agent_id);
        """
    )
    # Spoofing prevention: reject inserts for unknown agent_ids. This is
    # the trigger-based equivalent of the FK described in the design doc
    # section 4 (the actual governance_policies PK is composite, so a
    # plain FK on agent_id alone is not supported).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION governance_wrapper_reg_agent_exists()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM governance_policies
                WHERE agent_id = NEW.agent_id
            ) THEN
                RAISE EXCEPTION
                  'wrapper registration rejected: agent_id % not found in governance_policies',
                  NEW.agent_id
                USING ERRCODE = 'foreign_key_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        DROP TRIGGER IF EXISTS trg_wrapper_reg_agent_exists
            ON governance_wrapper_registrations;
        CREATE TRIGGER trg_wrapper_reg_agent_exists
            BEFORE INSERT ON governance_wrapper_registrations
            FOR EACH ROW
            EXECUTE FUNCTION governance_wrapper_reg_agent_exists();
        """
    )


def downgrade() -> None:
    """Drop the F9 wrapper registry table and its spoofing-prevention trigger."""
    op.execute(
        "DROP TRIGGER IF EXISTS trg_wrapper_reg_agent_exists "
        "ON governance_wrapper_registrations"
    )
    op.execute("DROP FUNCTION IF EXISTS governance_wrapper_reg_agent_exists()")
    op.execute("DROP INDEX IF EXISTS ix_wrapper_reg_agent")
    op.execute("DROP INDEX IF EXISTS ix_wrapper_reg_last_seen")
    op.execute("DROP TABLE IF EXISTS governance_wrapper_registrations")
